#!/bin/bash
set -e
echo "=== Verificación de Scripts Capibara6 ==="
echo ""
echo "[1/4] Verificando permisos..."
ls -lh *.sh | grep -E "(start|stop|quick)"
echo ""
echo "[2/4] Verificando sintaxis..."
bash -n start-capibara6.sh && echo "✓ start-capibara6.sh OK"
bash -n quick-start.sh && echo "✓ quick-start.sh OK"
bash -n stop-capibara6.sh && echo "✓ stop-capibara6.sh OK"
echo ""
echo "[3/4] Verificando archivos necesarios..."
[ -f docker-compose.yml ] && echo "✓ docker-compose.yml"
[ -f backend/server.py ] && echo "✓ backend/server.py"
[ -f INICIO-RAPIDO.md ] && echo "✓ INICIO-RAPIDO.md"
[ -f SERVICIOS.md ] && echo "✓ SERVICIOS.md"
echo ""
echo "[4/4] Verificando requisitos del sistema..."
python3 --version 2>/dev/null && echo "✓ Python instalado" || echo "✗ Python no instalado"
docker --version 2>/dev/null && echo "✓ Docker instalado" || echo "✗ Docker no instalado (instalar para usar)"
docker-compose --version 2>/dev/null && echo "✓ Docker Compose instalado" || echo "✗ Docker Compose no instalado (instalar para usar)"
echo ""
echo "=== Verificación Completada ==="
echo ""
echo "Para iniciar Capibara6:"
echo "  ./start-capibara6.sh"
